### PR TITLE
Added simple OpenMC notebook

### PR DESCRIPTION
**Pull request by jo-hall**

### CODE REVIEW

**Comment by jo-hall** [comment]
Added notebook from Friday's meeting
- added TBR tally
- Total flux in burner
- Total heating in burner

**Review by RemDelaporteMathurin — COMMENTED** [review]
I would move the model to a python script that can be imported in different files or notebooks.
Plus I would definitely avoid having absolute paths hard coded in the code, as it makes the work harder to reproduce.

@eepeterson what do you think?

**Comment by eepeterson** [comment]
I agree. I'd recommend using regular python scripts for building models and running simulations. I would use jupyter notebooks only for the post-processing and analysis.

**Comment by RemDelaporteMathurin** [comment]
@j-fletcher you shouldn't have merged this!!!!! 😢 

@josephb-hall will open another PR

**Pull request merged**
